Introduce updated cypress test (#3167)
* upgrade cypress to `8.3.1`

* reinitialise cypress

1. keeping examples for reference
2. consistent with code structure in `src`

* wrap login to separate cypress command

* refactor auth test - store user in fixture

* wrap patient create into cy command

* wrap facility crud as cy command

* refactor facility spec into its

* facility spec refactored, session persist command added

* refactored profile edit spec

* added locations, inventory tests

but running them still pending

* just initialise some test boilerplate

* add user_crud test boilerplate with todos

* user spec doing

* added sample test spec boilerplate

* persist localstorage for avoiding repeated logins

due to recaptcha prompt

* fix error

* fix user test as possible

skipped it for some time

* sample test basic test added

* sample list basic test added

* add facility inventory basic tests

* delete cypress examples

* fixing death_report test

* add shifting manage, filter tests

* added boilerplate tests for external_results, resource

* change in convention
every folder will have its same name spec file denoting basic features of that page
for example: `assets.spec.js` in `assets_spec`

* add name to user select

* fix shifting filter test

* download button in shifting test fixed
bug found `Cannot read property of undefined(res) in BoardView.tsx` to be fix

* fix download error -
TypeError: Cannot read properties of undefined (reading 'data')
    at triggerDownload (BoardView.tsx:72)

* fix download error -
TypeError: Cannot read properties of undefined (reading 'data')
    at triggerDownload (ResourceBoardView.tsx:61)

* fix resource test

* resource filter test added
test for airbnb's date picker component remaining

* add test for airbnb's date picker in filters

* complete black test for external results

* generate random username of length 10

* fix assets tests

* fix assets filter test

* fix forgot password test

* fix death report test

* fix patient test

* fix sample tests

* fix user tests

* correct test describe names

* ''

* removing unnecessary commands

* fix errors

* shift facility class to spec itself for now

* adding typescript only for future conversion

* prettier

* add auth test

* add boilerplate for other feature tests

* fix auth test

* upgrade cypress to `8.7.0`

* add cypress workflow

* fixing cypress workflow

* --

* make parallel run

* fixing deploy error

all jobs in a workflow runs on same vm i think.

* Delete cypress.yml

* Merge upstream cypress and migrate to cypress 10

* Fix facility type

* Update cypress

* Fix login captcha issue

* Fix types

* Introduce appropriate types on cypress files

* Apply ts types to all cypress files

* Update .gitignore

* Change login with api on roles cypress test

* Remove yarn.lock

* Change verification of token from `access` to `refresh`

* Remove extra comments in commands

* Revert token verification from `refresh` to `access`

* Fix eslint errors

* Remove comments and whitespace

* Update test and fix errors

* Update Cypress 10.4.0

* Fix delayed UI loading in browsers

* Fix profile click timeout

* Fix cypress phone search error

* Changed inventory test based on UI change

* Updated tests based on new UI  errors

* Fix User Crud Cypress test cases

* Fix shifting Cypress test case erros

* Fix assets button error on cypress

* Remove facility delete from cypress tests

* FIx button click for filters under resources

* Yet another cypress test error fix

* Cypress Version Update; Fix User CRUD Tests

* Minor Fixes

* Add force action to prevent errors

* fix (cypress): changed missing staff user

Co-authored-by: Abhinandan Arya <abhinandanarya06122000@gmail.com>
Co-authored-by: Gigin George <mail.gigin@gmail.com>
Co-authored-by: Khavin Shankar <khavinshankar@gmail.com>